### ISSUE TITLE
Quote a reply option

### ISSUE THREAD

**Issue by Marri** [glowfic-constellation/glowfic#1722] opened 2023-05-05 05:27 UTC
Add an option to a reply - possibly using a " icon? - where if you click it, it will preload the New Reply form with the text of that reply in a block quote. Could be a link or javascript or both, have not considered deeply.

**Comment by Throne3d** [comment] 2023-10-15 15:27
Dupe of #23

**Closed by Throne3d** 2023-10-15 15:27 UTC
